# Generated by Django 4.2.16 on 2024-11-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12)),
                ('role', models.CharField(choices=[('ADM', 'admin'), ('REG', 'regular')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
